[assembly: System.Reflection.AssemblyTitle("SETUNA优化 by tylearymf")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyProduct("SETUNA")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) 2008 CLEARUP")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCompany("clearunit")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("4483e561-8b3e-427d-98a4-e0e821b7bf2f")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyFileVersion("2.5.8")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]

